### ISSUE TITLE
Space between urls

### ISSUE THREAD

**Issue by unicodeveloper** [emeka-osuagwu/ACADA#15]
Look at this snapshot, look down at the status bar, there is space in the url specifically "PHP PROGRAMMING" which is wrong and risky. If you intend using the title of the video for the url, then you should create a slug for the title ( slugs replace spaces with hyphens ) or else just use the video id.

<img width="960" alt="screen shot 2015-11-28 at 5 44 02 pm" src="https://cloud.githubusercontent.com/assets/2946769/11452412/ad1748b0-95f7-11e5-80c8-f800a140fa63.png">

**Comment by emeka-osuagwu** [comment]
Fixed
